# Generated by Django 2.2 on 2020-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
