# Generated by Django 2.2 on 2020-12-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_star_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star_ratings',
        ),
    ]
