# Generated by Django 2.2 on 2020-12-26 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
        ('reviews', '0006_auto_20201226_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
