# Generated by Django 2.2 on 2020-12-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20201226_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='product',
        ),
    ]
