# Generated by Django 2.2 on 2020-12-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20201226_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_posted',
        ),
    ]
