# Generated by Django 2.2 on 2020-12-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_posted',
        ),
    ]
