# Generated by Django 2.2 on 2020-12-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
