# Generated by Django 2.2 on 2020-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('tag', models.CharField(max_length=254)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
